app/database/models/data_cliente.py
from peewee import Model, CharField, DateTimeField
from app.database.database import db
import datetime


class Cliente(Model):
    nome = CharField()
    email = CharField()
    data_creation = DateTimeField(default=datetime.datetime.now)

    class Meta:
        database = db

app/__init__.py
from flask import Flask
from configuration import configure_all


app = Flask(__name__)


configure_all(app)

app/routes/cliente.py
from flask import Blueprint, render_template, request
from app.database.models.data_cliente import Cliente


cliente_route = Blueprint('cliente', __name__)


@cliente_route.route('/')
def lista_cliente():
    clientes = Cliente.select()

    return render_template('lista_cliente.html', clientes=clientes)


@cliente_route.route('/', methods=['POST'])
def inserir_cliente():
    # Inserir os dados do cliente.
    data = request.json

    novo_usuario = Cliente.create(
        nome=data['nome'],
        email=data['email']
    )

    return render_template('item_cliente.html', cliente=novo_usuario)


@cliente_route.route('/new')
def form_cliente():
    # Formulário para cadastrar um cliente.
    return render_template('form_cliente.html')


@cliente_route.route('/<int:cliente_id>')
def detalhe_cliente(cliente_id):
    # Exibir detalhes do cliente.
    cliente = Cliente.get_by_id(cliente_id)

    return render_template('detalhe_cliente.html', cliente=cliente)


@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_cliente(cliente_id):
    # Formulário para editar um cliente.
    cliente = Cliente.get_by_id(cliente_id)

    return render_template('form_cliente.html', cliente=cliente)


@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def update_cliente(cliente_id):
    # Atualizar informações do cliente.
    data = request.json

    cliente_editado = Cliente.get_by_id(cliente_id)
    cliente_editado.nome = data['nome']
    cliente_editado.email = data['email']
    cliente_editado.save()

    return render_template('item_cliente.html', cliente=cliente_editado)


@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def delete_cliente(cliente_id):
    # Deletar informações do cliente.
    cliente = Cliente.get_by_id(cliente_id)
    cliente.delete_instance()

    return {'deleted': 'Ok'}

app/routes/home.py
from flask import Blueprint, render_template


home_route = Blueprint('home', __name__)


@home_route.route('/')
def index():
    return render_template('index.html')

app/templates/detalhe_cliente.html
<ul>
    <li>ID: {{ cliente.id }}</li>
    <li>Nome: {{ cliente.nome }}</li>
    <li>E-MAIL: {{ cliente.email }}</li>
</ul>

app/templates/form_cliente.html
<form class="c-form" 
        {% if cliente %} 
            action="{{ url_for('cliente.update_cliente', cliente_id=cliente.id) }}"
        {% else %} 
            action="{{ url_for('cliente.inserir_cliente') }}"
        {% endif %} 
        
        method="{% if cliente %}PUT{% else %}POST{% endif %}" 
        
        {% if cliente %}
            c-swap="#cliente-{{ cliente.id }}"
        {% else %}
            c-append="#lista_cliente"
        {% endif %}
        
        c-reload-container="true">
    
    <div class="mb-3">
        <label class="form-label">Nome</label>
        
        <input type="text" class="form-control" name="nome" {% if cliente %}value="{{ cliente.nome }}"{% endif %}>
    </div>
    
    <div class="mb-3">
        <label class="form-label">Email</label>
        
        <input type="text" class="form-control" name="email" {% if cliente %}value="{{ cliente.email }}"{% endif %}>
    </div>
    
    <button id="btn_add" type="submit" class="btn btn-primary">
        {% if cliente %} 
            Salvar 
        {% else %} 
            Criar 
        {% endif %}
    </button>
</form>

app/templates/index.html
<!doctype html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Gestão de Usuário</title>
</head>

<body>
    <div class="container">
        <h1 class="source">Gestão de Usuários</h1>

        <!-- Formulário add cliente -->
        <div id="form-cliente" c-container="{{ url_for('cliente.form_cliente') }}"></div>

        <hr>

        <h1 class="source">Lista de Clientes</h1>

        <!-- Lista de clientes -->
        <div c-container="{{ url_for('cliente.lista_cliente') }}"></div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>

                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body" id="exibir-cliente"></div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
</body>

</html>

app/templates/item_cliente.html
<tr id="cliente-{{ cliente.id }}">
    <th scope="row"> {{ cliente.id }} </th>
    <td> {{ cliente.nome }} </td>
    <td> {{ cliente.email }} </td>

    <td>
        <button class="btn btn-secondary" c-get="{{ url_for('cliente.detalhe_cliente', cliente_id=cliente.id) }}"
            c-target="#exibir-cliente" data-bs-toggle="modal" data-bs-target="#exampleModal">Ver</button>

        <button class="btn btn-primary" c-get="{{ url_for('cliente.form_edit_cliente', cliente_id=cliente.id) }}"
            c-target="#form-cliente">Editar</button>

        <button class="btn btn-danger" c-remove-closest="tr"
            c-delete="{{ url_for('cliente.delete_cliente', cliente_id=cliente.id) }}">Deletar</button>
    </td>
</tr>

app/templates/lista_cliente.html
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Email</th>
            <th scope="col">Ações</th>
        </tr>
    </thead>

    <tbody id="lista_cliente">
        {% for cliente in clientes %}

            {% include 'item_cliente.html' %}

        {% endfor %}
    </tbody>
</table>